ARG JAVA_VERSION="17"
FROM openjdk:${JAVA_VERSION}-jdk-alpine

ARG KUBECTL_VERSION="v1.19.4"
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
